export const DICT: Record<string, string> = {
  the: "o / a",
  and: "e",
  is: "é",
  are: "são",
  was: "era / foi",
  were: "eram / foram",
  have: "ter / têm",
  this: "isso / este",
  that: "aquilo / que",
  with: "com",
  for: "para",
  you: "você",
  me: "eu / me",
  my: "meu / minha",
  your: "seu / sua",
  we: "nós",
  they: "eles / elas",
  he: "ele",
  she: "ela",
  it: "isso",
  not: "não",
  no: "não",
  yes: "sim",
  what: "o quê",
  how: "como",
  who: "quem",
  where: "onde",
  when: "quando",
  do: "fazer / faz",
  did: "fez / fazia",
  can: "pode / consigo",
  could: "poderia",
  would: "iria / gostaria",
  know: "saber / conhecer",
  think: "pensar / acho",
  just: "apenas / só",
  like: "gostar / como",
  get: "conseguir / pegar",
  going: "indo / vai",
  come: "vir / venha",
  back: "voltar / de volta",
  good: "bom / boa",
  time: "tempo / vez",
  look: "olhar / parecer",
  see: "ver",
  want: "querer",
  need: "precisar",
  okay: "tudo bem",
  ok: "ok",
  right: "certo / direito",
  here: "aqui",
  there: "lá / ali",
  really: "realmente",
  something: "algo / alguma coisa",
  nothing: "nada",
  everything: "tudo",
  always: "sempre",
  never: "nunca",
  maybe: "talvez",
  because: "porque",
  sorry: "desculpe",
  please: "por favor",
  thank: "agradecer",
  thanks: "obrigado",
  hello: "olá",
  hey: "ei / oi",
  hi: "oi",
  bye: "tchau",
  love: "amor / amar",
  friend: "amigo",
  friends: "amigos",
  life: "vida",
  home: "lar / casa",
  work: "trabalho",
  day: "dia",
  night: "noite",
  people: "pessoas",
  guy: "cara / sujeito",
  guys: "pessoal / rapazes",
  help: "ajudar / ajuda",
  wait: "esperar",
  tell: "contar / dizer",
  said: "disse",
  say: "dizer / falar",
  talk: "conversar / falar",
  take: "pegar / levar",
  make: "fazer",
  little: "pouco / pequeno",
  much: "muito",
  very: "muito",
  still: "ainda",
  again: "de novo",
  now: "agora",
  then: "então",
  too: "também / demais",
  also: "também",
  fine: "bem / ótimo",
  great: "ótimo",
  sure: "claro / com certeza",
  actually: "na verdade",
  gonna: "vou / vai",
  gotta: "tenho que",
  wanna: "quero / quer",
  kinda: "tipo / meio que",
  yeah: "sim / é",
};

export function lookup(word: string): string | null {
  return DICT[word.toLowerCase()] ?? null;
}
